version: "3.9"

services:
  postgres:
    container_name: final_appointments_container
    image: postgres:14.11-alpine3.19
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - PG_DATA=$PG_DATA
    ports:
      - "127.0.0.1::5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql

  app:
    depends_on:
      - postgres
    build: .
    image: app:latest
    restart: always
    env_file: ./.env
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url" : "jdbc:postgresql://postgres:$PG_PORT/$POSTGRES_DB?useSSL=false",
          "spring.datasource.driver-class-name" : "org.postgresql.Driver",
          "spring.datasource.username" : "$POSTGRES_USER",
          "spring.datasource.password" : "$POSTGRES_PASSWORD",
          "spring.datasource.hikari.maximum-pool-size" : "20",
          "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local
